# 전자책 AI 이미지 생성 서비스 설정

# ComfyUI 서버 주소
comfyui_server: "100.100.53.32:8288"

# 벡터 데이터베이스 설정
vector_db:
  path: "./99_vectorstore/e_book_db"
  collection: "the_wizard_of_oz"
  embedding_model: "text-embedding-3-small"

# 이미지 생성 기본 파라미터
image_generation:
  default_steps: 20
  default_cfg: 1.0
  default_width: 1024
  default_height: 1024
  default_lora_strength: 0.8
  default_sampler: "euler"
  default_scheduler: "simple"

# Flux 모델 설정
flux_model:
  unet: "flux1-krea-dev_fp8_scaled.safetensors"
  lora: "pp-storybook_rank2_bf16.safetensors"
  vae: "ae.safetensors"
  clip_l: "clip_l.safetensors"
  clip_t5: "t5xxl_fp16.safetensors"